export type ReportCadence = "weekly" | "monthly" | "quarterly" | "yearly";
export type ReportStatus = "generating" | "complete" | "failed";

export interface ReportHighlight {
  type: "positive" | "negative" | "neutral";
  metric: string;
  observation: string;
}

/**
 * The full structured JSON stored in the DB and rendered on the frontend.
 *
 * Reliability contract:
 *   - All numeric fields (overview, topPages counts, etc.) are computed in
 *     TypeScript from ClickHouse data and NEVER sourced from LLM output.
 *   - The LLM produces only: summary, highlights, recommendations.
 *   - This prevents number hallucination — the LLM can reference numbers in
 *     its prose, but cannot alter them.
 */
export interface AiReportStructuredSummary {
  period: {
    start: string; // ISO date string
    end: string;
    cadence: ReportCadence;
  };
  // Computed in TypeScript — never from LLM
  overview: {
    pageviews: number;
    sessions: number;
    uniqueVisitors: number;
    bounceRate: number | null;
    avgSessionDuration: number; // seconds
    pageviewsChange: number | null; // % vs previous period; null = no prior data
    sessionsChange: number | null;
    usersChange: number | null;
    bounceRateChange: number | null;
  };
  // Computed in TypeScript — never from LLM
  topPages: Array<{ page: string; sessions: number; percentage: number }>;
  topReferrers: Array<{ referrer: string; sessions: number; percentage: number }>;
  topCountries: Array<{ country: string; sessions: number; percentage: number }>;
  deviceBreakdown: Array<{ device: string; sessions: number; percentage: number }>;
  /** Optional — only present when goals are configured for the site */
  goals?: Array<{ name: string; conversions: number; rate: number }>;
  /** Optional — new vs returning visitor split for the period */
  newVsReturning?: { newVisitors: number; returningVisitors: number; newPercentage: number };
  /** Optional — only present when Google Search Console is connected */
  gscTopQueries?: Array<{ query: string; clicks: number; impressions: number; position: number }>;
  /** Optional — only present for Scale-tier sites */
  scaleEnrichment?: ScaleEnrichment;
  // Generated by LLM — text only
  highlights: ReportHighlight[];
  /** 2–3 sentence plain-language narrative summarising the period. */
  summary: string;
  /** 2–3 concrete, actionable recommendations derived from the data. */
  recommendations: string[];
}

/**
 * The narrow schema the LLM is asked to produce.
 * Contains ONLY text fields — no numbers whatsoever.
 */
export interface LlmTextOutput {
  summary: string;
  highlights: ReportHighlight[];
  recommendations: string[];
}

/** Cadences that Pro subscribers are eligible for. */
export const PRO_CADENCES: ReportCadence[] = ["weekly"];

/** All cadences — Scale subscribers get all. */
export const SCALE_CADENCES: ReportCadence[] = ["weekly", "monthly", "quarterly", "yearly"];

/** Minimum days of existing pageview data required before we attempt a report. */
export const MIN_DATA_DAYS: Record<ReportCadence, number> = {
  weekly: 7,
  monthly: 30,
  quarterly: 90,
  yearly: 365,
};

/**
 * Returns the percentage change between two values, rounded to 1 decimal place.
 * Returns null if the base is zero or absent (no prior period data to compare).
 */
export function pctChange(current: number, previous: number | null | undefined): number | null {
  if (!previous || previous === 0) return null;
  return Math.round(((current - previous) / previous) * 100 * 10) / 10;
}

// ---------------------------------------------------------------------------
// Scale-only enrichment types
// ---------------------------------------------------------------------------

export interface PageMover {
  page: string;
  currentSessions: number;
  prevSessions: number;
  delta: number;       // positive = gained, negative = lost
  isNew: boolean;      // true if page did not appear in the previous period's top pages
}

export interface ChannelMixItem {
  channel: string;
  currentSessions: number;
  prevSessions: number;
  currentPercentage: number;
  prevPercentage: number;
}

export interface GoalTrend {
  name: string;
  conversions: number;
  rate: number;            // % of sessions this period
  prevConversions: number;
  prevRate: number;
  rateChange: number | null; // % change in conversion rate vs prev period
}

export interface CampaignSummary {
  campaign: string;
  sessions: number;
  percentage: number;
}

export interface EntryNextPage {
  entryPage: string;
  nextPage: string;
  sessions: number;  // sessions that went entry → next
}

export interface PeakTrafficWindow {
  peakDays: string[];  // e.g. ["Tuesday", "Wednesday"]
  peakHour: number;    // 0-23 UTC
}

export interface TrendPoint {
  periodStart: string;
  periodEnd: string;
  sessions: number;
  pageviews: number;
  bounceRate: number | null;
}

export interface ScaleEnrichment {
  pageMovers: {
    gainers: PageMover[];
    losers: PageMover[];
    newEntrants: PageMover[];
  };
  channelMix: ChannelMixItem[];
  goalTrends?: GoalTrend[];
  campaigns?: CampaignSummary[];
  entryNextPages: EntryNextPage[];
  peakTrafficWindow: PeakTrafficWindow;
  trendHistory?: TrendPoint[];  // monthly: 3 pts; quarterly: 4 pts; yearly: 2 pts
}
